name: dart_web
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl4x:
    git:
      url: git@github.com:dart-lang/i18n.git
      path: pkgs/intl4x
      ref: addCopyWith
  pubspec_lock_parse: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
