name: dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  intl4x: ^0.11.0
  pubspec_lock_parse: ^2.2.0

dev_dependencies:
  archive: ^4.0.4
  lints: ^5.1.1
  native_assets_cli: ^0.7.3
  test: ^1.21.0
