name: dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl4x: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.4
  build_web_compilers: ^4.0.3
  lints: ^2.0.0
  test: ^1.21.0
