name: dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  intl4x: ^0.8.1

dev_dependencies:
  archive: ^3.4.10
  lints: ^3.0.0
  native_assets_cli: ^0.4.2
  test: ^1.21.0
