name: Run Rust tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  rust_lint:
    strategy:
      fail-fast: false
      matrix:
        icu4x-version: [ '1.3', '1.4', '1.5', '2.0-beta1', '2.0-beta2', '2.0' ]
    name: Lint ICU4X Rust executor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.81"
          components: rustfmt, clippy
          default: true
      - uses: actions-rs/cargo@v1
        name: "Run Clippy"
        with:
          command: clippy
          args: --all-targets --all-features --manifest-path executors/rust/${{ matrix.icu4x-version }}/Cargo.toml
      - uses: actions-rs/cargo@v1
        name: "Run Rustfmt"
        with:
          command: fmt
          args: --manifest-path executors/rust/${{ matrix.icu4x-version }}/Cargo.toml -- --check
      - name: "Run Rustfmt (executor code)"
        run: rustfmt executors/rust/src/** --check
      - name: "Run Rustfmt (common code)"
        run: rustfmt executors/rust/common/** --check
  
