name: Run Rust tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  rust_lint:
    strategy:
      matrix:
        icu4x-version:
          - 1.3
          - 1.4
    name: Lint the executor code for ICU4X
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73
          components: rustfmt, clippy
          default: true
      - uses: actions-rs/cargo@v1
        name: "Run Clippy"
        with:
          command: clippy
          args: --all-targets --all-features --manifest-path executors/rust/${{ icu4x-version }}/Cargo.toml
      - uses: actions-rs/cargo@v1
        name: "Run Rustfmt"
        with:
          command: fmt
          args: --manifest-path executors/rust/${{ icu4x-version }}/Cargo.toml -- --check
  
