on:
  push:
    paths:
    - 'executors/rust/**'
    - '.github/**'
  pull_request:
    paths: 
    - 'executors/rust/**'
    - '.github/**'

name: Run Rust tests

jobs:
  rust_lint:
    name: Lint the rust executor code on submission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61
          components: rustfmt, clippy
          default: true
      - uses: actions-rs/cargo@v1
        name: "Run Clippy"
        with:
          command: clippy
          args: --all-targets --all-features --manifest-path executors/rust/Cargo.toml
      - uses: actions-rs/cargo@v1
        name: "Run Rustfmt"
        with:
          command: fmt
          args: --manifest-path executors/rust/Cargo.toml -- --check
  
